Repository knative-extensions/kn-plugin-diag, pull requests merged in 2021-11, with the labels that each got.

#95 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/L, lgtm, approved

#94 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/L, lgtm, approved

#96 Document maturity levels in sandbox
  readme.md
Labels: cla: yes, size/XS, lgtm, approved

#98 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#99 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#100 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/S, lgtm, approved

#101 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/XS, lgtm, approved

#102 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: cla: yes, size/L, lgtm, approved

#104 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved
