Repository knative-extensions/kn-plugin-diag, pull requests merged in 2021-07, with the labels that each got.

#61 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#64 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#63 drop releasibility action
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/L

#66 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#67 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#68 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
