Repository knative-extensions/kn-plugin-diag, pull requests merged in 2021-05, with the labels that each got.

#30 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#33 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#36 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#34 missing license header and updates to pkg/*
  pkg/command/diagnose/servingConfiguration.go
  pkg/models/conditionInfoConfig.go
  pkg/models/diagNode.go
  pkg/models/keyInfoConfig.go
  pkg/utils/ui.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/controller/OWNERS
  vendor/knative.dev/pkg/hash/OWNERS
  vendor/knative.dev/pkg/injection/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/logging/OWNERS
  vendor/knative.dev/pkg/metrics/OWNERS
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/pkg/reconciler/OWNERS
  vendor/knative.dev/pkg/test/OWNERS
  vendor/knative.dev/pkg/tracing/config/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/knative.dev/serving/pkg/gc/OWNERS
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/XL

#37 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#40 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/hack/OWNERS
  vendor/knative.dev/hack/OWNERS_ALIASES
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/controller/OWNERS
  vendor/knative.dev/pkg/hash/OWNERS
  vendor/knative.dev/pkg/injection/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/logging/OWNERS
  vendor/knative.dev/pkg/metrics/OWNERS
  vendor/knative.dev/pkg/network/OWNERS
  vendor/knative.dev/pkg/reconciler/OWNERS
  vendor/knative.dev/pkg/test/OWNERS
  vendor/knative.dev/pkg/tracing/config/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/gc/OWNERS
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#38 fix the panic in table
  pkg/utils/printableresource.go
  pkg/utils/table.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#41 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#43 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#44 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#46 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
