Repository knative-extensions/kn-plugin-diag, pull requests merged in 2021-03, with the labels that each got.

#12 add initial utils
  cmd/main.go
  go.mod
  go.sum
  pkg/command/diagnose/service.go
  pkg/utils/connectionCfg.go
  pkg/utils/fetcher.go
  pkg/utils/printableresource.go
  pkg/utils/table.go
Labels: approved, cla: yes, lgtm, size/XL

#13 add the original code in Nov.2020
  cmd/main.go
  pkg/command/diagnose/service.go
Labels: approved, cla: yes, lgtm, size/L

#17 [Automated] Format Go code
  cmd/main.go
  pkg/command/diagnose/service.go
Labels: approved, cla: yes, lgtm, size/XS

#18 [Automated] Format markdown
  readme.md
Labels: approved, cla: yes, lgtm, size/S

#19 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XL

#20 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#23 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS
